DELIMITER //

CREATE TRIGGER T1
AFTER INSERT ON s1
FOR EACH ROW
BEGIN
    INSERT INTO s2 (roll, name) VALUES (NEW.roll, NEW.name);
END;
//

DELIMITER ;

DELIMITER //
CREATE TRIGGER T2
AFTER UPDATE ON s1
FOR EACH ROW
BEGIN
    INSERT INTO s2 (roll, name) VALUES (NEW.roll, OLD.name);
END;
//
DELIMITER ;

DELIMITER //
CREATE TRIGGER T3
AFTER UPDATE ON s1
FOR EACH ROW
BEGIN
    INSERT INTO s2 (roll, name) VALUES (OLD.roll, NEW.name);
END;
//
DELIMITER ;

DELIMITER //
CREATE TRIGGER T4
AFTER UPDATE ON s1
FOR EACH ROW
BEGIN
    INSERT INTO s2 (roll, name) VALUES (NEW.roll, NEW.name);
END;
//
DELIMITER ;

DELIMITER //
CREATE TRIGGER T5
AFTER DELETE ON s1
FOR EACH ROW
BEGIN
    INSERT INTO s2 (roll, name) VALUES (OLD.roll, OLD.name);
END;
//
DELIMITER ;

DELIMITER //

CREATE TRIGGER T6
BEFORE INSERT ON s1
FOR EACH ROW
BEGIN
    IF NEW.roll = 11 THEN 
        SET NEW.roll = 3; 
    END IF;
    INSERT INTO s2 (roll, name) VALUES (NEW.roll, NEW.name);
END;
//

DELIMITER ;

DELIMITER //

CREATE TRIGGER T7
BEFORE UPDATE ON s1
FOR EACH ROW
BEGIN
    IF old.roll = 75 THEN 
        SET NEW.roll = 73; 
    END IF;
    INSERT INTO s2 (roll, name) VALUES (NEW.roll, NEW.name);
END;
//

DELIMITER ;

